name: flutter_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  intl: ^0.18.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_svg: ^2.0.10+1

flutter:
  uses-material-design: true
  assets:
  - assets/images/rectangle_2.jpeg
  - assets/vectors/vector_167_x2.svg
  - assets/vectors/vector_10_x2.svg
  - assets/vectors/vector_80_x2.svg
  - assets/images/rectangle_91.jpeg
  - assets/images/shape_2.jpeg
  - assets/images/rectangle_87.jpeg
  - assets/images/drools_removebg_preview_1.png
  - assets/images/rectangle_89.jpeg
  - assets/vectors/vector_86_x2.svg
  - assets/vectors/vector_23_x2.svg
  - assets/vectors/vector_13_x2.svg
  - assets/vectors/vector_62_x2.svg
  - assets/vectors/vector_47_x2.svg
  - assets/vectors/vector_144_x2.svg
  - assets/vectors/vector_50_x2.svg
  - assets/vectors/vector_49_x2.svg
  - assets/vectors/vector_45_x2.svg
  - assets/vectors/vector_122_x2.svg
  - assets/vectors/vector_79_x2.svg
  - assets/vectors/vector_154_x2.svg
  - assets/vectors/vector_155_x2.svg
  - assets/vectors/vector_76_x2.svg
  - assets/vectors/vector_14_x2.svg
  - assets/vectors/bxmap_2_x2.svg
  - assets/vectors/vector_72_x2.svg
  - assets/vectors/vector_3_x2.svg
  - assets/vectors/vector_25_x2.svg
  - assets/vectors/vector_6_x2.svg
  - assets/vectors/vector_1_x2.svg
  - assets/images/ellipse_4.png
  - assets/images/ellipse_11.jpeg
  - assets/images/ellipse_8.png
  - assets/vectors/vector_58_x2.svg
  - assets/vectors/vector_117_x2.svg
  - assets/vectors/vector_113_x2.svg
  - assets/vectors/vector_68_x2.svg
  - assets/vectors/vector_81_x2.svg
  - assets/vectors/vector_118_x2.svg
  - assets/images/ellipse_8.png
  - assets/images/unsplashd_hirbh_9_en_6_i.jpeg
  - assets/images/unsplash_lm_goenusq_1_c.jpeg
  - assets/images/ellipse_4.png
  - assets/images/oh_my_woof_removebg_preview_1.png
  - assets/images/pet_image_2.png
  - assets/images/snoutcamp_removebg_preview_1.png
  - assets/images/ellipse_6.png
  - assets/images/drools_removebg_preview_1.png
  - assets/vectors/vector_2_x2.svg
  - assets/vectors/vector_95_x2.svg
  - assets/vectors/star_2_x2.svg
  - assets/vectors/vector_89_x2.svg
  - assets/vectors/vector_51_x2.svg
  - assets/vectors/services_illustration_x2.svg
  - assets/vectors/star_x2.svg
  - assets/vectors/vector_69_x2.svg
  - assets/vectors/vector_64_x2.svg
  - assets/vectors/vector_73_x2.svg
  - assets/vectors/vector_159_x2.svg
  - assets/vectors/vector_85_x2.svg
  - assets/vectors/vector_59_x2.svg
  - assets/vectors/vector_114_x2.svg
  - assets/vectors/vector_29_x2.svg
  - assets/vectors/group_1_x2.svg
  - assets/vectors/vector_78_x2.svg
  - assets/vectors/checkup_x2.svg
  - assets/vectors/star_1_x2.svg
  - assets/vectors/vector_52_x2.svg
  - assets/vectors/vector_163_x2.svg
  - assets/vectors/vector_164_x2.svg
  - assets/vectors/vector_104_x2.svg
  - assets/vectors/polygon_4_x2.svg
  - assets/vectors/vector_150_x2.svg
  - assets/images/cute_dog_cat_hanging_over_260_nw_174918233_ezgif_com_webp_to_png_converter_removebg_preview_1.png
  - assets/vectors/vector_93_x2.svg
  - assets/vectors/arrow_x2.svg
  - assets/vectors/vector_28_x2.svg
  - assets/vectors/container_2_x2.svg
  - assets/images/ellipse_8.png
  - assets/images/ellipse_4.png
  - assets/vectors/vector_5_x2.svg
  - assets/vectors/tablerpaw_filled_x2.svg
  - assets/vectors/vector_70_x2.svg
  - assets/vectors/vector_38_x2.svg
  - assets/vectors/rectangle_104_x2.svg
  - assets/vectors/polygon_2_x2.svg
  - assets/vectors/polygon_1_x2.svg
  - assets/vectors/rectangle_103_x2.svg
  - assets/vectors/vector_153_x2.svg
  - assets/vectors/vector_115_x2.svg
  - assets/vectors/vector_123_x2.svg
  - assets/vectors/polygon_3_x2.svg
  - assets/vectors/vector_158_x2.svg
  - assets/vectors/vector_15_x2.svg
  - assets/images/drools_removebg_preview_1.png
  - assets/images/shape_2.jpeg
  - assets/vectors/vector_74_x2.svg
  - assets/vectors/vector_x2.svg
  - assets/vectors/vector_147_x2.svg
  - assets/vectors/vector_36_x2.svg
  - assets/vectors/vector_11_x2.svg
  - assets/vectors/polygon_11_x2.svg
  - assets/vectors/vector_106_x2.svg
  - assets/vectors/vector_110_x2.svg
  - assets/vectors/vector_105_x2.svg
  - assets/vectors/vector_32_x2.svg
  - assets/vectors/vector_55_x2.svg
  - assets/vectors/vector_141_x2.svg
  - assets/vectors/vector_39_x2.svg
  - assets/vectors/vector_168_x2.svg
  - assets/images/rectangle_21.jpeg
  - assets/vectors/vector_129_x2.svg
  - assets/vectors/vector_82_x2.svg
  - assets/vectors/vector_143_x2.svg
  - assets/vectors/vector_133_x2.svg
  - assets/images/ellipse_4.png
  - assets/images/unsplashp_wrtbo_bxces_2.jpeg
  - assets/images/unsplashp_wrtbo_bxces_1.jpeg
  - assets/images/ellipse_8.png
  - assets/images/unsplashp_wrtbo_bxces.jpeg
  - assets/vectors/vector_140_x2.svg
  - assets/vectors/vector_71_x2.svg
  - assets/vectors/vector_77_x2.svg
  - assets/vectors/vector_152_x2.svg
  - assets/vectors/vector_60_x2.svg
  - assets/vectors/vector_121_x2.svg
  - assets/vectors/vector_127_x2.svg
  - assets/vectors/distance_icon_x2.svg
  - assets/vectors/time_x2.svg
  - assets/vectors/vector_61_x2.svg
  - assets/vectors/container_x2.svg
  - assets/vectors/vector_165_x2.svg
  - assets/vectors/vector_30_x2.svg
  - assets/vectors/vector_41_x2.svg
  - assets/images/rectangle_82.jpeg
  - assets/vectors/vector_84_x2.svg
  - assets/vectors/vector_102_x2.svg
  - assets/vectors/group_x2.svg
  - assets/vectors/container_1_x2.svg
  - assets/vectors/vector_53_x2.svg
  - assets/vectors/vector_9_x2.svg
  - assets/vectors/vector_33_x2.svg
  - assets/vectors/vector_27_x2.svg
  - assets/vectors/vector_7_x2.svg
  - assets/vectors/vector_120_x2.svg
  - assets/vectors/vector_98_x2.svg
  - assets/vectors/vector_18_x2.svg
  - assets/vectors/vector_103_x2.svg
  - assets/vectors/vector_148_x2.svg
  - assets/vectors/vector_37_x2.svg
  - assets/vectors/vector_35_x2.svg
  - assets/vectors/vector_22_x2.svg
  - assets/vectors/vector_139_x2.svg
  - assets/images/rectangle_911.jpeg
  - assets/images/rectangle_872.jpeg
  - assets/images/rectangle_891.jpeg
  - assets/images/shape.png
  - assets/vectors/vector_101_x2.svg
  - assets/vectors/vector_16_x2.svg
  - assets/vectors/vector_169_x2.svg
  - assets/vectors/vector_88_x2.svg
  - assets/vectors/vector_149_x2.svg
  - assets/vectors/vector_107_x2.svg
  - assets/vectors/vector_125_x2.svg
  - assets/vectors/vector_67_x2.svg
  - assets/vectors/vector_132_x2.svg
  - assets/vectors/vector_26_x2.svg
  - assets/vectors/vector_157_x2.svg
  - assets/vectors/vector_42_x2.svg
  - assets/vectors/vector_137_x2.svg
  - assets/vectors/vector_44_x2.svg
  - assets/vectors/vector_116_x2.svg
  - assets/vectors/vector_146_x2.svg
  - assets/vectors/vector_54_x2.svg
  - assets/vectors/vector_43_x2.svg
  - assets/vectors/vector_63_x2.svg
  - assets/vectors/vector_57_x2.svg
  - assets/vectors/bxmap_1_x2.svg
  - assets/images/unsplash_fhtdk_ywykh_e.jpeg
  - assets/images/unsplash_ww_6_ba_kxgdm_q.jpeg
  - assets/images/unsplashxy_ipnaa_yt_g.jpeg
  - assets/images/image_1.png
  - assets/images/pet_image_2.png
  - assets/images/unsplash_lm_goenusq_1_c.jpeg
  - assets/images/unsplashd_hirbh_9_en_6_i.jpeg
  - assets/images/image.png
  - assets/vectors/star_44_x2.svg
  - assets/vectors/vector_19_x2.svg
  - assets/vectors/vector_100_x2.svg
  - assets/vectors/star_45_x2.svg
  - assets/vectors/star_25_x2.svg
  - assets/vectors/star_34_x2.svg
  - assets/vectors/star_24_x2.svg
  - assets/vectors/star_41_x2.svg
  - assets/vectors/vector_156_x2.svg
  - assets/vectors/star_21_x2.svg
  - assets/vectors/star_31_x2.svg
  - assets/vectors/star_35_x2.svg
  - assets/vectors/star_13_x2.svg
  - assets/vectors/star_12_x2.svg
  - assets/vectors/star_42_x2.svg
  - assets/vectors/star_3_x2.svg
  - assets/vectors/vector_21_x2.svg
  - assets/vectors/star_36_x2.svg
  - assets/vectors/star_15_x2.svg
  - assets/vectors/star_46_x2.svg
  - assets/vectors/star_23_x2.svg
  - assets/vectors/web_icon_x2.svg
  - assets/vectors/vector_75_x2.svg
  - assets/vectors/vector_136_x2.svg
  - assets/vectors/star_32_x2.svg
  - assets/vectors/star_33_x2.svg
  - assets/vectors/star_22_x2.svg
  - assets/vectors/star_43_x2.svg
  - assets/vectors/vector_111_x2.svg
  - assets/vectors/star_4_x2.svg
  - assets/vectors/star_16_x2.svg
  - assets/vectors/email_icon_x2.svg
  - assets/vectors/star_11_x2.svg
  - assets/vectors/star_26_x2.svg
  - assets/vectors/star_14_x2.svg
  - assets/vectors/star_1_x2.svg
  - assets/vectors/vector_87_x2.svg
  - assets/vectors/star_2_x2.svg
  - assets/images/shape_1.jpeg
  - assets/images/rectangle_871.jpeg
  - assets/images/rectangle_89.jpeg
  - assets/images/rectangle_91.jpeg
  - assets/vectors/vector_134_x2.svg
  - assets/vectors/vector_94_x2.svg
  - assets/vectors/vector_91_x2.svg
  - assets/vectors/vector_65_x2.svg
  - assets/vectors/vector_128_x2.svg
  - assets/vectors/vector_126_x2.svg
  - assets/vectors/vector_138_x2.svg
  - assets/vectors/vector_24_x2.svg
  - assets/vectors/vector_56_x2.svg
  - assets/vectors/vector_166_x2.svg
  - assets/vectors/vector_160_x2.svg
  - assets/vectors/bxmap_x2.svg
  - assets/vectors/vector_97_x2.svg
  - assets/vectors/vector_46_x2.svg
  - assets/vectors/vector_131_x2.svg
  - assets/vectors/vector_12_x2.svg
  - assets/vectors/vector_161_x2.svg
  - assets/vectors/vector_96_x2.svg
  - assets/vectors/vector_124_x2.svg
  - assets/vectors/vector_40_x2.svg
  - assets/vectors/vector_4_x2.svg
  - assets/images/ellipse_4.png
  - assets/vectors/vector_145_x2.svg
  - assets/vectors/vector_135_x2.svg
  - assets/vectors/vector_8_x2.svg
  - assets/vectors/vector_48_x2.svg
  - assets/vectors/vector_112_x2.svg
  - assets/vectors/vector_31_x2.svg
  - assets/vectors/vector_34_x2.svg
  - assets/vectors/vector_130_x2.svg
  - assets/vectors/vector_119_x2.svg
  - assets/vectors/vector_17_x2.svg
  - assets/vectors/vector_151_x2.svg
  - assets/vectors/vector_66_x2.svg
  - assets/vectors/vector_162_x2.svg
  - assets/vectors/vector_92_x2.svg
  - assets/vectors/vector_108_x2.svg
  - assets/vectors/vector_20_x2.svg
  - assets/vectors/vector_90_x2.svg
  - assets/vectors/vector_142_x2.svg
  - assets/vectors/vector_99_x2.svg

